### ISSUE TITLE
Feature Request: Plugin for inwx API (DynDNS)

### ISSUE THREAD

**Issue by lebochequirit** [cznweb/arkos-pkgbuilds#39]
Dear all,

guess it's very useful to help people setting up a dynamic dns for their arkos.
I've found inwx (inetworx) as a domain registrar that offers an API for updating a DNS entry.

I think the users you aim for would love a plugin that lets them setup a DDNS via the inwx API with a few clicks.

Have a look at 
http://blog.philippklaus.de/2011/05/access-the-internetworx-xml-rpc-api-via-python/
and the API client package at
https://npmjs.org/package/inwx

Hope to have helped you. Carry on.

L.B.Q.R.

**Comment by peakwinter** [comment]
Closing in favour of issue on cznweb/arkos-applications
