### ISSUE TITLE
Support 64 bits architecture | Intel NUC

### ISSUE THREAD

**Issue by HLFH** [cznweb/arkos-pkgbuilds#52]
Hi,

It would be cool to support 64 bits architecture. [Intel NUC](http://www.intel.fr/content/www/fr/fr/nuc/overview.html) is a serious selfhosting trend and a nice fightback against [ARM single-board computers](https://en.wikipedia.org/wiki/List_of_single-board_computers).

Please support 64 bits.

Thanks in advance,
HLFH

**Comment by peakwinter** [comment]
We support installation on x64/64 machines now with our repositories (and have for a little while now). The tricky part remains installation - though this is made much easier via the conversion script for existing Arch installs, available [from the Downloads page](https://arkos.io/download). We will put in effort in the future for a graphical ISO-based installer for x86/64 as well.

Thanks!
